[2025-04-18T17:29:08.869+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T17:29:08.897+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_dag.get_data_task manual__2025-04-18T17:26:59.653863+00:00 [queued]>
[2025-04-18T17:29:08.909+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_dag.get_data_task manual__2025-04-18T17:26:59.653863+00:00 [queued]>
[2025-04-18T17:29:08.910+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-04-18T17:29:08.929+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_data_task> on 2025-04-18 17:26:59.653863+00:00
[2025-04-18T17:29:08.937+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=468) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-18T17:29:08.939+0000] {standard_task_runner.py:72} INFO - Started process 469 to run task
[2025-04-18T17:29:08.939+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transaction_dag', 'get_data_task', 'manual__2025-04-18T17:26:59.653863+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/transaction_dag.py', '--cfg-path', '/tmp/tmpfzzr5ebn']
[2025-04-18T17:29:08.941+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask get_data_task
[2025-04-18T17:29:08.990+0000] {task_command.py:467} INFO - Running <TaskInstance: transaction_dag.get_data_task manual__2025-04-18T17:26:59.653863+00:00 [running]> on host 317bb80a77ef
[2025-04-18T17:29:09.094+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transaction_dag' AIRFLOW_CTX_TASK_ID='get_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T17:26:59.653863+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T17:26:59.653863+00:00'
[2025-04-18T17:29:09.097+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T17:29:09.166+0000] {logging_mixin.py:190} INFO - Data fetched from customers table: [{'customer_id': 'C1', 'customer_name': 'Michelle Garcia', 'gender': 'Female', 'age': 30, 'province': 'DI Yogyakarta', 'city': 'Yogyakarta'}, {'customer_id': 'C2', 'customer_name': 'Timothy Matthews', 'gender': 'Male', 'age': 63, 'province': 'Banten', 'city': 'Pandeglang'}, {'customer_id': 'C3', 'customer_name': 'Judy Bailey', 'gender': 'Female', 'age': 18, 'province': 'Jawa Barat', 'city': 'Tasikmalaya'}, {'customer_id': 'C4', 'customer_name': 'Rachel Houston', 'gender': 'Female', 'age': 20, 'province': 'Jawa Barat', 'city': 'Sukabumi'}, {'customer_id': 'C5', 'customer_name': 'Jessica Andrade', 'gender': 'Male', 'age': 35, 'province': 'Jawa Barat', 'city': 'Ciamis'}]
[2025-04-18T17:29:09.168+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/ingest_data.py", line 82, in get_data
    insert_data(new_table_name, data, conn)
  File "/opt/airflow/dags/utils/ingest_data.py", line 42, in insert_data
    for key, value in row_data.items():
                      ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'
[2025-04-18T17:29:09.182+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=transaction_dag, task_id=get_data_task, run_id=manual__2025-04-18T17:26:59.653863+00:00, execution_date=20250418T172659, start_date=20250418T172908, end_date=20250418T172909
[2025-04-18T17:29:09.220+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T17:29:09.221+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task get_data_task ('str' object has no attribute 'items'; 469)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/ingest_data.py", line 82, in get_data
    insert_data(new_table_name, data, conn)
  File "/opt/airflow/dags/utils/ingest_data.py", line 42, in insert_data
    for key, value in row_data.items():
                      ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'
[2025-04-18T17:29:09.245+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T17:29:09.274+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T17:29:09.279+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
